### ISSUE TITLE
Add support for the new Bulk API Endpoint data structure 

### ISSUE THREAD

**Issue by georgev21** [venmo/QuizTrain#29]
It seems that the [latest TR release ](https://discuss.gurock.com/t/bulk-api-endpoint-changes-coming-soon/19537) came with some changes to the GET API endpoints:

E.g [get_cases](https://www.gurock.com/testrail/docs/api/reference/cases#getcases)
"These bulk endpoints will no longer return an array of all entities, but will instead return an object with additional pagination fields and an array of up to 250 entities."

New response content:
```
{"offset": 0,
  "limit": 250,
  "size": 250,
  "_links":{
    "next": "/api/v2/get_cases/1&limit=250&offset=250",
    "prev": null
  },
  "cases":[
	{ "id": 1, "title": "..", .. },
	{ "id": 2, "title": "..", .. },
	..
]
}
```

Any plans to add support for the new data structure in QuizTrain?

**Comment by daemedeor** [comment]
Hi, sorry for the length of time @georgev21, we're no longer maintaining the repo and are going to close it down shortly.
